package asic

import (
	"bytes"
	"os"
	"testing"

	"github.com/beevik/etree"
	"github.com/isri-pqc/go-xmlsig/canonicalizers"
	"github.com/isri-pqc/go-xmlsig/etreeutils"
	"github.com/isri-pqc/go-xmlsig/spec"
)

// TestGoldenSignedInfoCanonicalization verifies that xmlsig's C14N 1.1
// canonicalizer reproduces, byte-for-byte, the canonical SignedInfo of
// the EID signature fixture (golden file). SELF-CONSISTENCY PIN: the
// fixture and golden are generated by this repo's own testutil PKI via
// test/samples/gen (regenerate: go run ./test/samples/gen); the
// external interop proof (the fixture goldens) lives in the
// companion asice-compat harness.
func TestGoldenSignedInfoCanonicalization(t *testing.T) {
	sampleDir := "../test/samples"

	sigXML, err := os.ReadFile(sampleDir + "/signatures0EID.xml")
	if err != nil {
		t.Fatal(err)
	}
	golden, err := os.ReadFile(sampleDir + "/canonicalSignedInfoEID")
	if err != nil {
		t.Fatal(err)
	}

	doc := etree.NewDocument()
	if err := doc.ReadFromBytes(sigXML); err != nil {
		t.Fatal(err)
	}
	si := doc.FindElement("//ds:SignedInfo")
	if si == nil {
		t.Fatal("SignedInfo not found")
	}

	parentCtx, err := etreeutils.NSBuildParentContext(si)
	if err != nil {
		t.Fatal(err)
	}
	canon, err := canonicalizers.CanonicalizeSignedInfo(si, spec.CanonicalXML11AlgorithmId, parentCtx)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(canon, golden) {
		t.Fatalf("canonical mismatch: got %d bytes, want %d bytes\ngot:\n%s\nwant:\n%s",
			len(canon), len(golden), canon, golden)
	}
}
