package asic

import (
	"bytes"
	"crypto/sha256"
	"encoding/base64"
	"os"
	"strings"
	"testing"

	"github.com/beevik/etree"
	"github.com/isri-pqc/xmlsig/canonicalizers"
	"github.com/isri-pqc/xmlsig/etreeutils"
	"github.com/isri-pqc/xmlsig/spec"
)

// TestGoldenSignedPropertiesDigest cross-checks our C14N 1.1 output for
// the EID signature fixture's SignedProperties element: sha256 of our
// canonical bytes must equal the DigestValue the fixture carries for
// the SignedProperties reference (S0-RefId1).
//
// SELF-CONSISTENCY PIN: the fixture is generated by this repo's own
// testutil PKI via test/samples/gen (regenerate: go run
// ./test/samples/gen); the digest is the one the document signed, not
// an external value. The external interop proof (the collector's
// fixture digest) lives in the companion asice-compat harness.
func TestGoldenSignedPropertiesDigest(t *testing.T) {
	sigXML, err := os.ReadFile("../test/samples/signatures0EID.xml")
	if err != nil {
		t.Fatal(err)
	}

	doc := etree.NewDocument()
	if err := doc.ReadFromBytes(sigXML); err != nil {
		t.Fatal(err)
	}
	sp := doc.FindElement("//xades:SignedProperties")
	if sp == nil {
		t.Fatal("SignedProperties not found")
	}
	parentCtx, err := etreeutils.NSBuildParentContext(sp)
	if err != nil {
		t.Fatal(err)
	}
	canon, err := canonicalizers.CanonicalizeSignedInfo(sp, spec.CanonicalXML11AlgorithmId, parentCtx)
	if err != nil {
		t.Fatal(err)
	}

	// The fixture's DigestValue for the SignedProperties reference.
	want := spReferenceDigest(t, doc)
	got := sha256.Sum256(canon)
	if !bytes.Equal(got[:], want) {
		t.Fatalf("SP digest mismatch:\ngot  %x\nwant %x\ncanonical (%d bytes):\n%s", got, want, len(canon), canon)
	}
}

// spReferenceDigest returns the DigestValue bytes of the S0-RefId1
// (SignedProperties) reference of the signature document.
func spReferenceDigest(t *testing.T, doc *etree.Document) []byte {
	t.Helper()
	for _, ref := range doc.Root().FindElements("//ds:Reference") {
		if ref.SelectAttrValue("Id", "") != "S0-RefId1" {
			continue
		}
		dv := ref.FindElement("ds:DigestValue")
		if dv == nil {
			t.Fatal("S0-RefId1 reference has no DigestValue")
		}
		der, err := base64.StdEncoding.DecodeString(strings.TrimSpace(dv.Text()))
		if err != nil {
			t.Fatalf("decode S0-RefId1 DigestValue: %v", err)
		}
		return der
	}
	t.Fatal("S0-RefId1 reference not found")
	return nil
}
