// Package tsa implements RFC 3161 time-stamping: TimeStampReq/Resp
// codecs (stdlib ASN.1 only), an HTTP client, and validation of
// TimeStampTokens (TSTs).
//
// The validator mirrors the TST checks the Estonian e-voting collector
// (the library's interop target; see the README "Verification"
// section) applies to an RFC 3161 timestamp token: TSTInfo version 1,
// message imprint over the supplied data (SHA-256/384/512), nonce,
// signed-attribute integrity and CMS signature over them — for both RSA
// and ECDSA signers — plus a certificate chain check against supplied
// roots and the TSA KeyUsage/EKU time-stamping requirement.
//
// TimeStampToken support: the hermetic fixture TSTs in test/samples
// (generated by test/samples/gen over the testutil PKI) are
// ECDSA-SHA256; the collector's fixture TSTs (verified by the external
// acceptance harness, maintained outside this repo) are
// RSA-SHA512/SHA384. Both parse and
// validate through the same code paths.
package tsa

import (
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/asn1"
	"fmt"
	"math/big"
	"time"
)

// Media types (RFC 3161 section 2.5).
const (
	ContentTypeQuery = "application/timestamp-query"
	ContentTypeReply = "application/timestamp-reply"
)

// Well-known OIDs (RFC 3161 / RFC 5652 / CMS).
var (
	// OidSignedData is the ContentInfo content type of a
	// TimeStampToken (RFC 3161 section 2.4.2).
	OidSignedData = asn1.ObjectIdentifier{1, 2, 840, 113549, 1, 7, 2}
	// OidCTTSTInfo is the id-ct-TSTInfo content type inside the
	// token's EncapsulatedContentInfo (RFC 3161 section 2.4.2).
	OidCTTSTInfo = asn1.ObjectIdentifier{1, 2, 840, 113549, 1, 9, 16, 1, 4}

	// Message-imprint digest algorithm OIDs, RFC 3161 section 2.4.1.
	// Only these three are supported for validation (the set the
	// collector's TST checks accept). oidSHA1 is the signingCert
	// (RFC 5652) attribute
	// hash, which never appears in an imprint.
	oidSHA1   = asn1.ObjectIdentifier{1, 3, 14, 3, 2, 26}
	oidSHA256 = asn1.ObjectIdentifier{2, 16, 840, 1, 101, 3, 4, 2, 1}
	oidSHA384 = asn1.ObjectIdentifier{2, 16, 840, 1, 101, 3, 4, 2, 2}
	oidSHA512 = asn1.ObjectIdentifier{2, 16, 840, 1, 101, 3, 4, 2, 3}

	// CMS signature algorithm OIDs. Both RSA and ECDSA families are
	// accepted (the set the collector's TST checks accept).
	oidRSASHA256   = asn1.ObjectIdentifier{1, 2, 840, 113549, 1, 1, 11}
	oidRSASHA384   = asn1.ObjectIdentifier{1, 2, 840, 113549, 1, 1, 12}
	oidRSASHA512   = asn1.ObjectIdentifier{1, 2, 840, 113549, 1, 1, 13}
	oidECDSASHA256 = asn1.ObjectIdentifier{1, 2, 840, 10045, 4, 3, 2}
	oidECDSASHA384 = asn1.ObjectIdentifier{1, 2, 840, 10045, 4, 3, 3}
	oidECDSASHA512 = asn1.ObjectIdentifier{1, 2, 840, 10045, 4, 3, 4}
)

// signatureDigestOIDs maps a CMS signature algorithm OID (string
// key) to the digest algorithm OID it must be paired with, as the
// collector's TST checks pair them.
var signatureDigestOIDs = map[string]asn1.ObjectIdentifier{
	oidRSASHA256.String():   oidSHA256,
	oidRSASHA384.String():   oidSHA384,
	oidRSASHA512.String():   oidSHA512,
	oidECDSASHA256.String(): oidSHA256,
	oidECDSASHA384.String(): oidSHA384,
	oidECDSASHA512.String(): oidSHA512,
}

// TimeStampReq is an RFC 3161 TimeStampReq (section 2.4.1), the body of
// an application/timestamp-query request.
type TimeStampReq struct {
	// Version must be 1 (RFC 3161); the encoder omits the field when it
	// is 1, exactly as the wire format defines.
	Version int
	// MessageImprint is the digest of the data to be time-stamped.
	// HashedMessage is the digest value; the encoder does not hash
	// anything itself.
	MessageImprint MessageImprint
	// Nonce is optional; when present, a compliant TSA MUST echo it in
	// the TST.
	Nonce *big.Int
	// CertReq requests the TSA certificate in the token (compliant TSAs
	// include it anyway).
	CertReq bool
}

// MessageImprint pairs a digest algorithm with the digest value
// (RFC 3161 section 2.4.1).
type MessageImprint struct {
	// HashAlgorithm is the AlgorithmIdentifier of the digest (e.g.
	// SHA-256 with a NULL parameter).
	HashAlgorithm pkix.AlgorithmIdentifier
	// HashedMessage is the digest value over the data.
	HashedMessage []byte
}

// Encode serializes the request to DER.
func (r TimeStampReq) Encode() ([]byte, error) {
	if r.Version != 1 {
		return nil, fmt.Errorf("tsa: TimeStampReq Version must be 1, got %d", r.Version)
	}
	// Go's asn1 encoder does not apply the "default" tag on the way
	// out, so Version is set explicitly (the collector encodes it
	// explicitly too).
	req := tsRequest{
		Version:        1,
		MessageImprint: r.MessageImprint,
		Nonce:          r.Nonce,
		CertReq:        r.CertReq,
	}
	der, err := asn1.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("tsa: marshal TimeStampReq: %w", err)
	}
	return der, nil
}

// tsRequest is the RFC 3161 TimeStampReq layout. "default:1" on Version
// is decode-only (absent on the wire means 1); CertReq is omitted when
// false (the omitted form is RFC-conformant: BOOLEAN DEFAULT TRUE).
type tsRequest struct {
	Version        int `asn1:"default:1"`
	MessageImprint MessageImprint
	Nonce          *big.Int `asn1:"optional"`
	CertReq        bool     `asn1:"optional,omitempty"`
}

// ParseTimeStampReq parses a DER-encoded TimeStampReq.
func ParseTimeStampReq(der []byte) (TimeStampReq, error) {
	var raw tsRequest
	rest, err := asn1.Unmarshal(der, &raw)
	if err != nil {
		return TimeStampReq{}, fmt.Errorf("tsa: unmarshal TimeStampReq: %w", err)
	}
	if len(rest) > 0 {
		return TimeStampReq{}, fmt.Errorf("tsa: TimeStampReq has %d trailing bytes", len(rest))
	}
	req := TimeStampReq{
		Version:        raw.Version,
		MessageImprint: raw.MessageImprint,
		Nonce:          raw.Nonce,
		CertReq:        raw.CertReq,
	}
	if req.Version == 0 {
		req.Version = 1 // omitted on the wire
	}
	return req, nil
}

// TimeStampResp is an RFC 3161 TimeStampResp (section 2.4.2), the body
// of an application/timestamp-reply response.
type TimeStampResp struct {
	Status
	// TimeStampToken holds the token when Status is 0 (granted).
	TimeStampToken *TSToken
}

// Status is the PKIStatusInfo of a TimeStampResp (RFC 3161 section
// 2.4.2).
type Status struct {
	// Status is a pkiStatus value: 0 granted, 1 grantedWithMods, 2
	// rejection, 3 waiting, 4 revoked, 5 keyCompromise; 50-60 are
	// failure codes.
	Status int
	// StatusString is the optional status text.
	StatusString []string
	// FailInfo is the optional failure bit string.
	FailInfo asn1.BitString
}

type statusInfo struct {
	Status       int
	StatusString []string       `asn1:"optional"`
	FailInfo     asn1.BitString `asn1:"optional"`
}

// ParseTimeStampResp parses a DER-encoded TimeStampResp.
func ParseTimeStampResp(der []byte) (TimeStampResp, error) {
	// Unmarshal the status first; the remainder is the (optional)
	// TimeStampToken ContentInfo, taken byte-exact.
	var status statusInfo
	tokenDER, err := asn1.Unmarshal(der, &status)
	if err != nil {
		return TimeStampResp{}, fmt.Errorf("tsa: unmarshal TimeStampResp: %w", err)
	}
	resp := TimeStampResp{Status: Status{
		Status:       status.Status,
		StatusString: status.StatusString,
		FailInfo:     status.FailInfo,
	}}
	if len(tokenDER) > 0 {
		var ci contentInfo
		rest, err := asn1.Unmarshal(tokenDER, &ci)
		if err != nil {
			return TimeStampResp{}, fmt.Errorf("tsa: unmarshal TimeStampToken: %w", err)
		}
		if len(rest) > 0 {
			return TimeStampResp{}, fmt.Errorf("tsa: TimeStampResp has %d trailing bytes", len(rest))
		}
		resp.TimeStampToken = &TSToken{
			DER:         append([]byte(nil), tokenDER...),
			ContentType: ci.ContentType,
		}
	}
	return resp, nil
}

// TSToken is a TimeStampToken: a ContentInfo whose content type is
// id-signedData (RFC 3161 section 2.4.2).
type TSToken struct {
	// DER is the full token (ContentInfo) DER encoding; these are the
	// bytes embedded as xades:EncapsulatedTimeStamp.
	DER []byte
	// ContentType is the ContentInfo content type (id-signedData for
	// well-formed tokens).
	ContentType asn1.ObjectIdentifier
	// Content is the inner SignedData.
	Content SignedData
}

// SignedData is a CMS SignedData (RFC 5652 section 5.1).
type SignedData struct {
	Version          int
	DigestAlgorithms []pkix.AlgorithmIdentifier
	// EncapContentInfo is the content; for TSTs its type is
	// id-ct-TSTInfo.
	EncapContentInfo TSTContentInfo
	// Certificates are the certificates included in the token (typically
	// the TSA certificate).
	Certificates []*x509.Certificate
	SignerInfos  []SignerInfo
}

// TSTContentInfo is the token's EncapsulatedContentInfo.
type TSTContentInfo struct {
	// EContentType is the content type OID (id-ct-TSTInfo).
	EContentType asn1.ObjectIdentifier
	// TSTInfo is the parsed id-ct-TSTInfo content.
	TSTInfo *TSTInfo
	// EContent is the raw (DER) TSTInfo encoding.
	EContent []byte
}

// SignerInfo is a CMS SignerInfo (RFC 5652 section 5.3). Only the
// issuer-and-serial (version 1) and subject-key-identifier (version 3)
// identifier forms are recognized (matching the collector).
type SignerInfo struct {
	// Version: 1 (issuer + serial) or 3 (subject key identifier).
	Version int
	// IssuerAndSerial: the issuer name and serial of the signing
	// certificate (version 1).
	IssuerAndSerial *IssuerSerial
	// SubjectKeyIdentifier: the signing certificate's SKI (version 3).
	SubjectKeyIdentifier []byte

	DigestAlgorithm    pkix.AlgorithmIdentifier
	SignedAttrs        []SignedAttr
	SignatureAlgorithm pkix.AlgorithmIdentifier
	// Signature is the signature over the signed attributes.
	Signature []byte
}

// IssuerSerial identifies a certificate by issuer name and serial
// number.
type IssuerSerial struct {
	Issuer       pkix.RDNSequence
	SerialNumber *big.Int
}

// SignedAttr is one CMS signed attribute.
type SignedAttr struct {
	// AttrType is the attribute OID.
	AttrType asn1.ObjectIdentifier
	// AttrValue is the attribute value content (the SET content — the
	// single value).
	AttrValue []byte
	// attrValueTag is the full tag of the attribute value; it must be a
	// SET (0x31) per the CMS single-valued-attribute convention the
	// collector enforces.
	attrValueTag byte
}

// TSTInfo is an RFC 3161 TSTInfo (section 2.4.2).
type TSTInfo struct {
	// Version must be 1.
	Version int
	// Policy is the time-stamping policy OID.
	Policy asn1.ObjectIdentifier
	// MessageImprint is the digest of the time-stamped data.
	MessageImprint MessageImprint
	// SerialNumber is the token serial.
	SerialNumber *big.Int
	// GenTime is the time the token was generated.
	GenTime time.Time
	// Accuracy is the claimed time accuracy (zero when absent).
	Accuracy Accuracy
	// Ordering is true when ordering protection is requested.
	Ordering bool
	// Nonce, when non-nil, must echo the request nonce.
	Nonce *big.Int
	// Extensions is the (rarely used) extension list.
	Extensions []pkix.Extension
}

// Accuracy is the TSTInfo claimed time accuracy.
type Accuracy struct {
	Seconds int
	Millis  int
	Micros  int
}

// contentInfo is a CMS ContentInfo (RFC 5652 section 10.1).
type contentInfo struct {
	ContentType asn1.ObjectIdentifier
	Content     signedData `asn1:"explicit,tag:0"`
}

// signedData mirrors RFC 5652 section 5.1 (the shapes the collector's
// CMS unmarshal expects).
type signedData struct {
	Version          int
	DigestAlgorithms []pkix.AlgorithmIdentifier `asn1:"set"`
	EncapContentInfo encapsulatedContentInfo
	Certificates     []asn1.RawValue `asn1:"set,tag:0,optional"`
	SignerInfos      []cmsSignerInfo `asn1:"set"`
}

type encapsulatedContentInfo struct {
	RawContent   asn1.RawContent
	EContentType asn1.ObjectIdentifier
	EContent     []byte `asn1:"explicit,tag:0,optional"`
}

type cmsSignerInfo struct {
	Version int

	// Golang doesn't support ASN.1 CHOICE, so model the
	// SignerIdentifier as two optional fields (the collector's
	// approach).
	IssuerAndSerialNumber issuerAndSerialNumber `asn1:"optional"`
	SubjectKeyIdentifier  []byte                `asn1:"tag:0,optional"`

	DigestAlgorithm    pkix.AlgorithmIdentifier
	SignedAttrs        []cmsSignedAttribute `asn1:"set,tag:0,optional"`
	SignatureAlgorithm pkix.AlgorithmIdentifier
	Signature          []byte
}

type issuerAndSerialNumber struct {
	Issuer       pkix.RDNSequence
	SerialNumber *big.Int
}

type cmsSignedAttribute struct {
	AttrType  asn1.ObjectIdentifier
	AttrValue asn1.RawValue
}

// tstInfo mirrors the RFC 3161 TSTInfo shape the collector's
// unmarshal expects.
type tstInfo struct {
	Version        int
	Policy         asn1.ObjectIdentifier
	MessageImprint MessageImprint
	SerialNumber   *big.Int
	GenTime        time.Time
	Accuracy       accuracy         `asn1:"optional"`
	Ordering       bool             `asn1:"optional"`
	Nonce          *big.Int         `asn1:"optional"`
	Extensions     []pkix.Extension `asn1:"explicit,tag:1,optional"`
}

type accuracy struct {
	Seconds int `asn1:"optional"`
	Millis  int `asn1:"tag:0,optional"`
	Micros  int `asn1:"tag:1,optional"`
}
