// Validator unit tests: hermetic TSTs generated by the testutil PKI
// (newTestTSA, fixedNow reference time) — self-consistency pins. The
// fixture-interop tests (the TSTs embedded in the collector's fixtures
// testEIDTS.bdoc / testMIDTS.bdoc against trustTS.yaml) live in the
// external acceptance harness (maintained outside this repo).

package tsa

import (
	"crypto/rand"
	"crypto/x509"
	"math/big"
	"testing"
	"time"

	"github.com/isri-pqc/go-asice/testutil"
	tcrypto "github.com/isri-pqc/go-asice/tsa/crypto"
)

// fixedNow is the reference time for hermetic validator tests.
var fixedNow = time.Date(2026, 8, 27, 12, 0, 0, 0, time.UTC)

// newTestTSA returns a fresh test PKI and a TST over data at fixedNow
// (ECDSA-SHA256, the testutil shape).
func newTestTSA(t *testing.T, data []byte, opts testutil.TSTOptions) (*testutil.PKI, []byte) {
	t.Helper()
	opts.GenTime = fixedNow
	p, err := testutil.NewPKI(testutil.Options{Now: fixedNow})
	if err != nil {
		t.Fatalf("NewPKI: %v", err)
	}
	token, err := p.TimeStampToken(data, opts)
	if err != nil {
		t.Fatalf("TimeStampToken: %v", err)
	}
	return p, token
}

// withStdModules wires the standard-library crypto modules into v (the
// test default; an alternative backend implements the same interfaces).
func withStdModules(v *Validator) *Validator {
	v.DigestModule = tcrypto.NewStdDigestModule()
	v.SignatureVerifierModule = tcrypto.NewStdSignatureVerifierModule()
	v.ChainModule = tcrypto.NewStdCertificateChainModule()
	return v
}

// TestValidatorTestTST: a testutil TST validates for the exact data.
func TestValidatorTestTST(t *testing.T) {
	data := make([]byte, 2048)
	if _, err := rand.Read(data); err != nil {
		t.Fatalf("rand: %v", err)
	}
	nonce := new(big.Int).SetBytes([]byte{9, 8, 7, 6, 5})
	p, token := newTestTSA(t, data, testutil.TSTOptions{Nonce: nonce})

	v := withStdModules(&Validator{
		Roots:      []*x509.Certificate{p.Root.Certificate},
		TSTSigners: []*x509.Certificate{p.TSA.Certificate},
	})
	gen, err := v.Check(token, data, CheckOptions{Nonce: nonce, FreshnessCheck: true, Now: fixedNow})
	if err != nil {
		t.Fatalf("Validator.Check rejected the test TST: %v", err)
	}
	if !gen.Equal(fixedNow) {
		t.Errorf("genTime = %s, want %s", gen.UTC(), fixedNow)
	}
}

// TestValidatorTestTSTTampered: tampered data or TST bytes are rejected.
func TestValidatorTestTSTTampered(t *testing.T) {
	data := make([]byte, 1024)
	if _, err := rand.Read(data); err != nil {
		t.Fatalf("rand: %v", err)
	}
	p, token := newTestTSA(t, data, testutil.TSTOptions{})

	v := withStdModules(&Validator{
		Roots:      []*x509.Certificate{p.Root.Certificate},
		TSTSigners: []*x509.Certificate{p.TSA.Certificate},
	})
	// Tampered data.
	other := append([]byte(nil), data...)
	other[len(other)/2] ^= 0x42
	if _, err := v.Check(token, other, CheckOptions{FreshnessCheck: true, Now: fixedNow}); err == nil {
		t.Fatalf("Validator.Check accepted tampered data")
	}
	// Tampered token: flip bytes in the signature and imprint regions.
	for _, offset := range []int{150, 400, len(token) / 2, len(token) - 50} {
		corrupted := append([]byte(nil), token...)
		corrupted[offset] ^= 0xFF
		if _, err := v.Check(corrupted, data, CheckOptions{FreshnessCheck: true, Now: fixedNow}); err == nil {
			t.Errorf("Validator.Check accepted a TST with byte %d flipped", offset)
		}
	}
}

// TestValidatorNonceMismatch: a supplied nonce different from the TST's
// must be rejected; a matching nonce passes.
func TestValidatorNonce(t *testing.T) {
	data := make([]byte, 512)
	if _, err := rand.Read(data); err != nil {
		t.Fatalf("rand: %v", err)
	}
	given := new(big.Int).SetBytes([]byte{1, 2, 3, 4, 5, 6, 7, 8, 9, 10})
	p, token := newTestTSA(t, data, testutil.TSTOptions{Nonce: given})

	v := withStdModules(&Validator{
		Roots:      []*x509.Certificate{p.Root.Certificate},
		TSTSigners: []*x509.Certificate{p.TSA.Certificate},
	})
	if _, err := v.Check(token, data, CheckOptions{Nonce: given}); err != nil {
		t.Fatalf("matching nonce rejected: %v", err)
	}
	wrong := new(big.Int).Add(given, big.NewInt(1))
	if _, err := v.Check(token, data, CheckOptions{Nonce: wrong}); err == nil {
		t.Fatalf("wrong nonce accepted")
	}
}

// TestValidatorFreshnessBounds exercises the collector's genTime
// freshness windows (maxAge 1 minute, maxSkew 2 seconds) at the
// boundaries.
func TestValidatorFreshnessBounds(t *testing.T) {
	data := make([]byte, 256)
	if _, err := rand.Read(data); err != nil {
		t.Fatalf("rand: %v", err)
	}
	p, token := newTestTSA(t, data, testutil.TSTOptions{})
	v := withStdModules(&Validator{
		Roots:      []*x509.Certificate{p.Root.Certificate},
		TSTSigners: []*x509.Certificate{p.TSA.Certificate},
	})

	cases := []struct {
		name    string
		now     time.Time
		wantErr bool
	}{
		{"exact genTime", fixedNow, false},
		{"age 30s", fixedNow.Add(30 * time.Second), false},
		{"age 60s (boundary)", fixedNow.Add(60 * time.Second), false},
		{"age 61s", fixedNow.Add(61 * time.Second), true},
		{"skew 2s (boundary, gen 2s in the future)", fixedNow.Add(-2 * time.Second), false},
		{"gen 3s in the future", fixedNow.Add(-3 * time.Second), true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := v.Check(token, data, CheckOptions{FreshnessCheck: true, Now: tc.now})
			if (err != nil) != tc.wantErr {
				t.Fatalf("Check(now=%s) err=%v, wantErr=%v", tc.now.Sub(fixedNow), err, tc.wantErr)
			}
		})
	}
}

// TestValidatorWrongSigner: the TST signer must be among the configured
// signers.
func TestValidatorWrongSigner(t *testing.T) {
	data := make([]byte, 256)
	p, token := newTestTSA(t, data, testutil.TSTOptions{})

	// The container signer is not a TSA.
	v := withStdModules(&Validator{
		Roots:      []*x509.Certificate{p.Root.Certificate},
		TSTSigners: []*x509.Certificate{p.Signer.Certificate},
	})
	if _, err := v.Check(token, data, CheckOptions{}); err == nil {
		t.Fatalf("Validator.Check accepted a TST with an unconfigured signer")
	}

	// An untrusted root breaks the chain check.
	other, err := testutil.NewPKI(testutil.Options{Now: fixedNow})
	if err != nil {
		t.Fatalf("NewPKI: %v", err)
	}
	v2 := withStdModules(&Validator{
		Roots:      []*x509.Certificate{other.Root.Certificate},
		TSTSigners: []*x509.Certificate{p.TSA.Certificate},
	})
	if _, err := v2.Check(token, data, CheckOptions{}); err == nil {
		t.Fatalf("Validator.Check accepted a TST that does not chain to the configured root")
	}
}

// TestValidatorMissingConfig: empty Roots/TSTSigners are configuration
// errors.
func TestValidatorMissingConfig(t *testing.T) {
	data := make([]byte, 256)
	p, token := newTestTSA(t, data, testutil.TSTOptions{})

	v := &Validator{TSTSigners: []*x509.Certificate{p.TSA.Certificate}}
	if _, err := v.Check(token, data, CheckOptions{}); err == nil {
		t.Fatalf("Check with no Roots succeeded, want error")
	}
	v2 := &Validator{Roots: []*x509.Certificate{p.Root.Certificate}}
	if _, err := v2.Check(token, data, CheckOptions{}); err == nil {
		t.Fatalf("Check with no TSTSigners succeeded, want error")
	}
}
