// Validator unit tests: hermetic TSTs generated by the testutil PKI
// (newTestTSA, fixedNow reference time) — self-consistency pins. The
// fixture-interop tests (the TSTs embedded in the collector's fixtures
// testEIDTS.bdoc / testMIDTS.bdoc against trustTS.yaml) live in the
// external acceptance harness (maintained outside this repo).

package tsa

import (
	"bytes"
	"crypto"
	"crypto/rand"
	"crypto/sha256"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/asn1"
	"math/big"
	"sort"
	"testing"
	"time"

	"github.com/isri-pqc/go-asice/testutil"
	tcrypto "github.com/isri-pqc/go-asice/tsa/crypto"
)

// fixedNow is the reference time for hermetic validator tests.
var fixedNow = time.Date(2026, 8, 27, 12, 0, 0, 0, time.UTC)

// newTestTSA returns a fresh test PKI and a TST over data at fixedNow
// (ECDSA-SHA256, the testutil shape).
func newTestTSA(t *testing.T, data []byte, opts testutil.TSTOptions) (*testutil.PKI, []byte) {
	t.Helper()
	opts.GenTime = fixedNow
	p, err := testutil.NewPKI(testutil.Options{Now: fixedNow})
	if err != nil {
		t.Fatalf("NewPKI: %v", err)
	}
	token, err := p.TimeStampToken(data, opts)
	if err != nil {
		t.Fatalf("TimeStampToken: %v", err)
	}
	return p, token
}

// withStdModules wires the standard-library crypto modules into v (the
// test default; an alternative backend implements the same interfaces).
func withStdModules(v *Validator) *Validator {
	v.DigestModule = tcrypto.NewStdDigestModule()
	v.SignatureVerifierModule = tcrypto.NewStdSignatureVerifierModule()
	v.ChainModule = tcrypto.NewStdCertificateChainModule()
	return v
}

// TestValidatorTestTST: a testutil TST validates for the exact data.
func TestValidatorTestTST(t *testing.T) {
	data := make([]byte, 2048)
	if _, err := rand.Read(data); err != nil {
		t.Fatalf("rand: %v", err)
	}
	nonce := new(big.Int).SetBytes([]byte{9, 8, 7, 6, 5})
	p, token := newTestTSA(t, data, testutil.TSTOptions{Nonce: nonce})

	v := withStdModules(&Validator{
		Roots:      []*x509.Certificate{p.Root.Certificate},
		TSTSigners: []*x509.Certificate{p.TSA.Certificate},
	})
	gen, err := v.Check(token, data, CheckOptions{Nonce: nonce, FreshnessCheck: true, Now: fixedNow})
	if err != nil {
		t.Fatalf("Validator.Check rejected the test TST: %v", err)
	}
	if !gen.Equal(fixedNow) {
		t.Errorf("genTime = %s, want %s", gen.UTC(), fixedNow)
	}
}

// TestValidatorTestTSTTampered: tampered data or TST bytes are rejected.
func TestValidatorTestTSTTampered(t *testing.T) {
	data := make([]byte, 1024)
	if _, err := rand.Read(data); err != nil {
		t.Fatalf("rand: %v", err)
	}
	p, token := newTestTSA(t, data, testutil.TSTOptions{})

	v := withStdModules(&Validator{
		Roots:      []*x509.Certificate{p.Root.Certificate},
		TSTSigners: []*x509.Certificate{p.TSA.Certificate},
	})
	// Tampered data.
	other := append([]byte(nil), data...)
	other[len(other)/2] ^= 0x42
	if _, err := v.Check(token, other, CheckOptions{FreshnessCheck: true, Now: fixedNow}); err == nil {
		t.Fatalf("Validator.Check accepted tampered data")
	}
	// Tampered token: flip bytes in the signature and imprint regions.
	for _, offset := range []int{150, 400, len(token) / 2, len(token) - 50} {
		corrupted := append([]byte(nil), token...)
		corrupted[offset] ^= 0xFF
		if _, err := v.Check(corrupted, data, CheckOptions{FreshnessCheck: true, Now: fixedNow}); err == nil {
			t.Errorf("Validator.Check accepted a TST with byte %d flipped", offset)
		}
	}
}

// TestValidatorNonCanonicalSignedAttrs: a signature over the
// non-canonical (emission-order) encoding of the signed attributes
// must be rejected by checkSignature. The check verifies the
// signature over the canonical DER re-encoding (X.690 11.6) — the
// order BouncyCastle/DSS re-derive; a wire-order check would accept
// it (the leniency that let a mis-ordered hand-rolled TSA pass the
// Go gate while the Java gate failed).
func TestValidatorNonCanonicalSignedAttrs(t *testing.T) {
	data := make([]byte, 256)
	if _, err := rand.Read(data); err != nil {
		t.Fatalf("rand: %v", err)
	}
	p, token := newTestTSA(t, data, testutil.TSTOptions{})

	ts, err := Parse(token)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	attrs := ts.Content.SignerInfos[0].SignedAttrs // canonical wire order
	if len(attrs) != 4 {
		t.Fatalf("token has %d signed attributes, want 4", len(attrs))
	}
	byOID := make(map[string]SignedAttr, len(attrs))
	for _, a := range attrs {
		byOID[a.AttrType.String()] = a
	}

	v := withStdModules(&Validator{
		Roots:      []*x509.Certificate{p.Root.Certificate},
		TSTSigners: []*x509.Certificate{p.TSA.Certificate},
	})
	null := asn1.RawValue{FullBytes: asn1.NullBytes}
	sInfo := SignerInfo{
		DigestAlgorithm:    pkix.AlgorithmIdentifier{Algorithm: oidSHA256, Parameters: null},
		SignedAttrs:        attrs,
		SignatureAlgorithm: pkix.AlgorithmIdentifier{Algorithm: oidECDSASHA256, Parameters: null},
	}

	// Positive control: a signature over the canonical re-encoding verifies.
	canonical, err := canonicalSignedAttrsDER(attrs)
	if err != nil {
		t.Fatalf("encode canonical attrs: %v", err)
	}
	sum := sha256.Sum256(canonical)
	sigOK, err := p.TSA.PrivateKey.Sign(rand.Reader, sum[:], crypto.SHA256)
	if err != nil {
		t.Fatalf("sign canonical attrs: %v", err)
	}
	sInfo.Signature = sigOK
	if err := v.checkSignature(sInfo, p.TSA.Certificate); err != nil {
		t.Fatalf("checkSignature rejected a signature over the canonical attrs: %v", err)
	}

	// Negative: the non-canonical OID order (ct, md, st, sc — the
	// pre-fix pki/tsa emission order; the long messageDigest attribute
	// precedes the shorter signingTime) signed in that order, as a
	// mis-ordered TSA does.
	reordered := []SignedAttr{byOID[oidAttrContentType], byOID[oidAttrMessageDigest], byOID[oidAttrSigningTime], byOID[oidAttrSigningCert]}
	nonCanonical, err := signedAttrsDER(reordered)
	if err != nil {
		t.Fatalf("encode non-canonical attrs: %v", err)
	}
	sum = sha256.Sum256(nonCanonical)
	sig, err := p.TSA.PrivateKey.Sign(rand.Reader, sum[:], crypto.SHA256)
	if err != nil {
		t.Fatalf("sign non-canonical attrs: %v", err)
	}
	// The signature is valid over the non-canonical bytes — exactly
	// what a wire-order (pre-fix) verifier would accept.
	if err := p.TSA.Certificate.CheckSignature(x509.ECDSAWithSHA256, nonCanonical, sig); err != nil {
		t.Fatalf("signature does not verify over the non-canonical bytes: %v", err)
	}
	sInfoNon := sInfo
	sInfoNon.SignedAttrs = reordered
	sInfoNon.Signature = sig
	if err := v.checkSignature(sInfoNon, p.TSA.Certificate); err == nil {
		t.Fatalf("checkSignature accepted a signature over non-canonical signed-attribute order")
	}
}

// signedAttrsDER encodes attrs in slice order as the CMS SET OF (0x31):
// a plain-slice marshal carries no asn1 set tag, so no DER sorting
// happens — the emission order is preserved.
func signedAttrsDER(attrs []SignedAttr) ([]byte, error) {
	raw := make([]cmsSignedAttribute, 0, len(attrs))
	for _, a := range attrs {
		raw = append(raw, cmsSignedAttribute{AttrType: a.AttrType, AttrValue: asn1.RawValue{Tag: 17, IsCompound: true, Bytes: a.AttrValue}})
	}
	der, err := asn1.Marshal(raw)
	if err != nil {
		return nil, err
	}
	der[0] = 0x31 // SET OF
	return der, nil
}

// canonicalSignedAttrsDER is the same encoding in canonical DER order
// (X.690 11.6) — the bytes checkSignature verifies against.
func canonicalSignedAttrsDER(attrs []SignedAttr) ([]byte, error) {
	per := make([][]byte, 0, len(attrs))
	for _, a := range attrs {
		der, err := asn1.Marshal(cmsSignedAttribute{AttrType: a.AttrType, AttrValue: asn1.RawValue{Tag: 17, IsCompound: true, Bytes: a.AttrValue}})
		if err != nil {
			return nil, err
		}
		per = append(per, der)
	}
	sort.Slice(per, func(i, j int) bool { return bytes.Compare(per[i], per[j]) < 0 })
	raw := make([]asn1.RawValue, 0, len(per))
	for _, d := range per {
		raw = append(raw, asn1.RawValue{FullBytes: d})
	}
	der, err := asn1.Marshal(raw)
	if err != nil {
		return nil, err
	}
	der[0] = 0x31 // SET OF
	return der, nil
}

// TestValidatorNonceMismatch: a supplied nonce different from the TST's
// must be rejected; a matching nonce passes.
func TestValidatorNonce(t *testing.T) {
	data := make([]byte, 512)
	if _, err := rand.Read(data); err != nil {
		t.Fatalf("rand: %v", err)
	}
	given := new(big.Int).SetBytes([]byte{1, 2, 3, 4, 5, 6, 7, 8, 9, 10})
	p, token := newTestTSA(t, data, testutil.TSTOptions{Nonce: given})

	v := withStdModules(&Validator{
		Roots:      []*x509.Certificate{p.Root.Certificate},
		TSTSigners: []*x509.Certificate{p.TSA.Certificate},
	})
	if _, err := v.Check(token, data, CheckOptions{Nonce: given}); err != nil {
		t.Fatalf("matching nonce rejected: %v", err)
	}
	wrong := new(big.Int).Add(given, big.NewInt(1))
	if _, err := v.Check(token, data, CheckOptions{Nonce: wrong}); err == nil {
		t.Fatalf("wrong nonce accepted")
	}
}

// TestValidatorFreshnessBounds exercises the collector's genTime
// freshness windows (maxAge 1 minute, maxSkew 2 seconds) at the
// boundaries.
func TestValidatorFreshnessBounds(t *testing.T) {
	data := make([]byte, 256)
	if _, err := rand.Read(data); err != nil {
		t.Fatalf("rand: %v", err)
	}
	p, token := newTestTSA(t, data, testutil.TSTOptions{})
	v := withStdModules(&Validator{
		Roots:      []*x509.Certificate{p.Root.Certificate},
		TSTSigners: []*x509.Certificate{p.TSA.Certificate},
	})

	cases := []struct {
		name    string
		now     time.Time
		wantErr bool
	}{
		{"exact genTime", fixedNow, false},
		{"age 30s", fixedNow.Add(30 * time.Second), false},
		{"age 60s (boundary)", fixedNow.Add(60 * time.Second), false},
		{"age 61s", fixedNow.Add(61 * time.Second), true},
		{"skew 2s (boundary, gen 2s in the future)", fixedNow.Add(-2 * time.Second), false},
		{"gen 3s in the future", fixedNow.Add(-3 * time.Second), true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := v.Check(token, data, CheckOptions{FreshnessCheck: true, Now: tc.now})
			if (err != nil) != tc.wantErr {
				t.Fatalf("Check(now=%s) err=%v, wantErr=%v", tc.now.Sub(fixedNow), err, tc.wantErr)
			}
		})
	}
}

// TestValidatorWrongSigner: the TST signer must be among the configured
// signers.
func TestValidatorWrongSigner(t *testing.T) {
	data := make([]byte, 256)
	p, token := newTestTSA(t, data, testutil.TSTOptions{})

	// The container signer is not a TSA.
	v := withStdModules(&Validator{
		Roots:      []*x509.Certificate{p.Root.Certificate},
		TSTSigners: []*x509.Certificate{p.Signer.Certificate},
	})
	if _, err := v.Check(token, data, CheckOptions{}); err == nil {
		t.Fatalf("Validator.Check accepted a TST with an unconfigured signer")
	}

	// An untrusted root breaks the chain check.
	other, err := testutil.NewPKI(testutil.Options{Now: fixedNow})
	if err != nil {
		t.Fatalf("NewPKI: %v", err)
	}
	v2 := withStdModules(&Validator{
		Roots:      []*x509.Certificate{other.Root.Certificate},
		TSTSigners: []*x509.Certificate{p.TSA.Certificate},
	})
	if _, err := v2.Check(token, data, CheckOptions{}); err == nil {
		t.Fatalf("Validator.Check accepted a TST that does not chain to the configured root")
	}
}

// TestValidatorMissingConfig: empty Roots/TSTSigners are configuration
// errors.
func TestValidatorMissingConfig(t *testing.T) {
	data := make([]byte, 256)
	p, token := newTestTSA(t, data, testutil.TSTOptions{})

	v := &Validator{TSTSigners: []*x509.Certificate{p.TSA.Certificate}}
	if _, err := v.Check(token, data, CheckOptions{}); err == nil {
		t.Fatalf("Check with no Roots succeeded, want error")
	}
	v2 := &Validator{Roots: []*x509.Certificate{p.Root.Certificate}}
	if _, err := v2.Check(token, data, CheckOptions{}); err == nil {
		t.Fatalf("Check with no TSTSigners succeeded, want error")
	}
}
