package xades

import (
	"archive/zip"
	"crypto/x509"
	"encoding/base64"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
	"unicode"

	"github.com/beevik/etree"
)

// testNow is the shared reference time of the xades tests (single
// reference time, ADR 0001 §6).
var testNow = time.Date(2026, 8, 27, 10, 0, 0, 0, time.UTC)

// --- fixture shape comparison (semantic, layout-agnostic) ---

// shapeEqual asserts that got has the same element shape as want: same
// tag order, same attributes, same text with whitespace ignored
// (the rendered base64 is single-line, the fixture's is wrapped — the
// whitespace is not part of any value).
func shapeEqual(t *testing.T, path string, want, got *etree.Element) {
	t.Helper()
	if want.Space != got.Space || want.Tag != got.Tag {
		t.Errorf("%s: tag = %s, want %s", path, got.FullTag(), want.FullTag())
		return
	}
	wa, ga := attrMap(want), attrMap(got)
	for k, w := range wa {
		if ga[k] != w {
			t.Errorf("%s: attribute %s = %q, want %q", path, k, ga[k], w)
		}
	}
	for k, g := range ga {
		if _, ok := wa[k]; !ok {
			t.Errorf("%s: unexpected attribute %s = %q", path, k, g)
		}
	}
	wc, gc := want.ChildElements(), got.ChildElements()
	if len(wc) != len(gc) {
		t.Errorf("%s: %d element children, want %d", path, len(gc), len(wc))
		return
	}
	for i := range wc {
		shapeEqual(t, path+"/"+wc[i].FullTag(), wc[i], gc[i])
	}
	if stripSpace(want.Text()) != stripSpace(got.Text()) {
		t.Errorf("%s: text = %q, want %q", path, stripSpace(got.Text()), stripSpace(want.Text()))
	}
}

// attrMap maps an element's attributes by full key (prefix-qualified).
func attrMap(el *etree.Element) map[string]string {
	m := make(map[string]string, len(el.Attr))
	for _, a := range el.Attr {
		m[a.FullKey()] = a.Value
	}
	return m
}

// stripSpace removes all whitespace from s (base64 comparison form).
func stripSpace(s string) string {
	return strings.Map(func(r rune) rune {
		if unicode.IsSpace(r) {
			return -1
		}
		return r
	}, s)
}

// samplesDir holds the hermetic fixtures generated by this repo's own
// testutil PKI via test/samples/gen (provenance:
// test/samples/README.md).
const samplesDir = "../test/samples"

// readFixtureSignature returns a signature document: the .xml file
// itself, or META-INF/signatures0.xml extracted from the .bdoc.
func readFixtureSignature(t *testing.T, name string) string {
	t.Helper()
	path := filepath.Join(samplesDir, name)
	if strings.HasSuffix(name, ".bdoc") {
		zr, err := zip.OpenReader(path)
		if err != nil {
			t.Fatalf("open %s: %v", name, err)
		}
		defer zr.Close()
		for _, f := range zr.File {
			if f.Name != "META-INF/signatures0.xml" {
				continue
			}
			rc, err := f.Open()
			if err != nil {
				t.Fatal(err)
			}
			data, err := io.ReadAll(rc)
			if err != nil {
				t.Fatal(err)
			}
			return string(data)
		}
		t.Fatalf("META-INF/signatures0.xml not found in %s", name)
		return ""
	}
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

// fixtureKeyInfoCert parses the ds:X509Certificate of a fixture
// signature document.
func fixtureKeyInfoCert(t *testing.T, s string) *x509.Certificate {
	t.Helper()
	i := strings.Index(s, "<ds:X509Certificate>")
	j := strings.Index(s, "</ds:X509Certificate>")
	if i < 0 || j < 0 {
		t.Fatal("ds:X509Certificate not found in fixture")
	}
	der, err := base64.StdEncoding.DecodeString(
		strings.TrimSpace(s[i+len("<ds:X509Certificate>") : j]))
	if err != nil {
		t.Fatalf("decode fixture KeyInfo certificate: %v", err)
	}
	cert, err := x509.ParseCertificate(der)
	if err != nil {
		t.Fatalf("parse fixture KeyInfo certificate: %v", err)
	}
	return cert
}

// fixtureValue returns the TrimSpace'd base64 content between the
// opening tag tag (any attributes) and its closing tag in s.
func fixtureValue(t *testing.T, s, tag string) []byte {
	t.Helper()
	open := "<" + tag
	i := strings.Index(s, open)
	if i < 0 {
		t.Fatalf("%s not found in fixture", tag)
	}
	attr := strings.IndexByte(s[i:], '>')
	if attr < 0 {
		t.Fatalf("unterminated %s tag", tag)
	}
	j := strings.Index(s[i:], "</"+tag+">")
	if j < 0 {
		t.Fatalf("%s not closed in fixture", tag)
	}
	data, err := base64.StdEncoding.DecodeString(
		strings.TrimSpace(s[i+attr+1 : i+j]))
	if err != nil {
		t.Fatalf("decode %s: %v", tag, err)
	}
	return data
}
