package xades

import (
	"crypto/sha256"
	"encoding/base64"
	"regexp"
	"strings"
	"testing"
	"time"

	"github.com/beevik/etree"
	"github.com/isri-pqc/asice/testutil"
)

// TestSignedPropertiesMatchesEIDFixtureShape shape-compares the rendered
// SignedProperties against the SP subtree of the EID signature fixture
// (test/samples/signatures0EID.xml): same element order, attributes, and
// values.
//
// SELF-CONSISTENCY PIN: the fixture is generated by this repo's own
// testutil PKI via test/samples/gen; a SignaturePolicyIdentifier
// (legacy TM shape, absent from BES-clean fixtures) is compared with
// the element removed when present — the external interop proof (the
// collector's EID fixture, which carries the SPI) lives in the
// companion asice-compat harness. The layout (indentation,
// base64 line width) is house style and is pinned separately by the
// golden layout test.
func TestSignedPropertiesMatchesEIDFixtureShape(t *testing.T) {
	s := readFixtureSignature(t, "signatures0EID.xml")
	cert := fixtureKeyInfoCert(t, s)

	signingTime := fixtureSigningTime(t, s)
	files := fixtureFiles(t, s)

	// Fixture SP subtree with its SignaturePolicyIdentifier block
	// removed when present (nested in SignedSignatureProperties, the
	// legacy TM position).
	want := fixtureSPElement(t, s)
	if spi := want.FindElement("xades:SignedSignatureProperties/xades:SignaturePolicyIdentifier"); spi != nil {
		spi.Parent().RemoveChild(spi)
	}

	got, err := SignedProperties(0, stdDM(), cert, signingTime, files)
	if err != nil {
		t.Fatalf("SignedProperties: %v", err)
	}
	shapeEqual(t, "xades:SignedProperties", want, got)
}

// TestSignedPropertiesMatchesTSFixtureShape checks the same shape
// equality against the BES-clean SP of the hermetic TS fixture
// testEIDTS.bdoc (no SignaturePolicyIdentifier to strip).
func TestSignedPropertiesMatchesTSFixtureShape(t *testing.T) {
	s := readFixtureSignature(t, "testEIDTS.bdoc")
	cert := fixtureKeyInfoCert(t, s)

	got, err := SignedProperties(0, stdDM(), cert, fixtureSigningTime(t, s), fixtureFiles(t, s))
	if err != nil {
		t.Fatalf("SignedProperties: %v", err)
	}
	shapeEqual(t, "xades:SignedProperties", fixtureSPElement(t, s), got)
}

// fixtureSPElement parses the fixture signature document and returns its
// xades:SignedProperties element (the semantic fixture side of the
// shape comparison).
func fixtureSPElement(t *testing.T, s string) *etree.Element {
	t.Helper()
	d := etree.NewDocument()
	if err := d.ReadFromString(s); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	el := d.FindElement("//xades:SignedProperties")
	if el == nil {
		t.Fatal("xades:SignedProperties not found in fixture")
	}
	return el
}

// fixtureSigningTime extracts the xades:SigningTime of a fixture.
func fixtureSigningTime(t *testing.T, s string) time.Time {
	t.Helper()
	i := strings.Index(s, "<xades:SigningTime>")
	j := strings.Index(s, "</xades:SigningTime>")
	if i < 0 || j < 0 {
		t.Fatal("xades:SigningTime not found in fixture")
	}
	signingTime, err := time.Parse(time.RFC3339, s[i+len("<xades:SigningTime>"):j])
	if err != nil {
		t.Fatal(err)
	}
	return signingTime
}

// fixtureFiles extracts the signed data files of a fixture: one entry
// per SignedInfo file reference, in reference order, with the
// DataObjectFormat media type.
func fixtureFiles(t *testing.T, s string) []File {
	t.Helper()
	refs := refIDURIRE.FindAllStringSubmatch(s, -1)
	if len(refs) == 0 {
		t.Fatal("no data file references found in fixture")
	}
	files := make([]File, 0, len(refs))
	for _, r := range refs {
		files = append(files, File{Name: r[2], MediaType: dofMimeFor(t, s, r[1])})
	}
	return files
}

// goldenSignedProperties pins the exact rendered bytes of
// SignedProperties for one deterministic input, so the 2-space indent /
// single-line base64 house layout cannot drift.
func TestSignedPropertiesGoldenLayout(t *testing.T) {
	p, err := testutil.NewPKI(testutil.Options{Now: testNow})
	if err != nil {
		t.Fatal(err)
	}
	files := []File{{Name: "test.txt", MediaType: "application/octet-stream"}}
	sp, err := SignedProperties(0, stdDM(), p.Signer.Certificate, testNow, files)
	if err != nil {
		t.Fatalf("SignedProperties: %v", err)
	}
	got := renderSPWrapper(t, sp)
	digest := sha256.Sum256(p.Signer.Certificate.Raw)
	want := strings.NewReplacer(
		"@@DIGEST@@", base64.StdEncoding.EncodeToString(digest[:]),
		"@@ISSUER@@", IssuerName(p.Signer.Certificate),
		"@@SERIAL@@", p.Signer.Certificate.SerialNumber.String(),
	).Replace(goldenSPLayout)
	if got != want {
		t.Errorf("SP layout drifted:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// renderSPWrapper builds the golden's minimal signature document
// (asic:XAdESSignatures → ds:Signature → ds:Object → sp), indents it,
// and returns the serialized bytes.
func renderSPWrapper(t *testing.T, sp *etree.Element) string {
	t.Helper()
	doc := etree.NewDocument()
	root := doc.CreateElement("asic:XAdESSignatures")
	root.CreateAttr("xmlns:asic", NSASIC)
	root.CreateAttr("xmlns:ds", NSDSIG)
	root.CreateAttr("xmlns:xades", NSXAdES)
	sig := root.CreateElement("ds:Signature")
	sig.CreateAttr("Id", "S0")
	obj := sig.CreateElement("ds:Object")
	obj.AddChild(sp)
	doc.Indent(2)
	s, err := doc.WriteToString()
	if err != nil {
		t.Fatalf("serialize SP wrapper: %v", err)
	}
	return s
}

const goldenSPLayout = `<asic:XAdESSignatures xmlns:asic="http://uri.etsi.org/02918/v1.2.1#" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xades="http://uri.etsi.org/01903/v1.3.2#">
  <ds:Signature Id="S0">
    <ds:Object>
      <xades:SignedProperties Id="S0-SignedProperties">
        <xades:SignedSignatureProperties>
          <xades:SigningTime>2026-08-27T10:00:00Z</xades:SigningTime>
          <xades:SigningCertificate>
            <xades:Cert>
              <xades:CertDigest>
                <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                <ds:DigestValue>@@DIGEST@@</ds:DigestValue>
              </xades:CertDigest>
              <xades:IssuerSerial>
                <ds:X509IssuerName>@@ISSUER@@</ds:X509IssuerName>
                <ds:X509SerialNumber>@@SERIAL@@</ds:X509SerialNumber>
              </xades:IssuerSerial>
            </xades:Cert>
          </xades:SigningCertificate>
        </xades:SignedSignatureProperties>
        <xades:SignedDataObjectProperties>
          <xades:DataObjectFormat ObjectReference="#S0-RefId0">
            <xades:MimeType>application/octet-stream</xades:MimeType>
          </xades:DataObjectFormat>
        </xades:SignedDataObjectProperties>
      </xades:SignedProperties>
    </ds:Object>
  </ds:Signature>
</asic:XAdESSignatures>
`

var (
	// File references: <ds:Reference Id="S0-RefId0" URI="test.txt">.
	// The SignedProperties reference carries a Type attribute between Id
	// and URI and is therefore not matched.
	refIDURIRE = regexp.MustCompile(`<ds:Reference Id="(S0-RefId\d+)" URI="([^"]+)"`)
	// <xades:DataObjectFormat ObjectReference="#S0-RefId0"> with its
	// MimeType child.
	dofRE = regexp.MustCompile(`<xades:DataObjectFormat ObjectReference="#(S0-RefId\d+)">\s*<xades:MimeType>([^<]*)</xades:MimeType>`)
)

func dofMimeFor(t *testing.T, s, refID string) string {
	t.Helper()
	for _, m := range dofRE.FindAllStringSubmatch(s, -1) {
		if m[1] == refID {
			return m[2]
		}
	}
	t.Fatalf("DataObjectFormat for %s not found in fixture", refID)
	return ""
}

// spElement inserts sp into a minimal signature document and returns the
// xades:SignedProperties element as it sits in the parsed tree.
func spElement(t *testing.T, sp *etree.Element) *etree.Element {
	t.Helper()
	doc := etree.NewDocument()
	root := doc.CreateElement("asic:XAdESSignatures")
	root.CreateAttr("xmlns:asic", NSASIC)
	root.CreateAttr("xmlns:ds", NSDSIG)
	root.CreateAttr("xmlns:xades", NSXAdES)
	sig := root.CreateElement("ds:Signature")
	sig.CreateAttr("Id", "S0")
	obj := sig.CreateElement("ds:Object")
	obj.AddChild(sp)
	el := doc.FindElement("//xades:SignedProperties")
	if el == nil {
		t.Fatal("xades:SignedProperties not found")
	}
	return el
}

// TestCheckSignedProperties runs the xades self-checks against our
// rendered output: the positive case must pass, and each mutation the
// Estonian e-voting collector's property verification rejects must be
// caught.
func TestCheckSignedProperties(t *testing.T) {
	p, err := testutil.NewPKI(testutil.Options{Now: testNow})
	if err != nil {
		t.Fatal(err)
	}
	files := []File{{Name: "test.txt", MediaType: "application/octet-stream"}}
	sp, err := SignedProperties(0, stdDM(), p.Signer.Certificate, testNow, files)
	if err != nil {
		t.Fatalf("SignedProperties: %v", err)
	}
	if err := CheckSignedProperties(stdDM(), 0, spElement(t, sp), p.Signer.Certificate, files); err != nil {
		t.Fatalf("positive case failed: %v", err)
	}

	mutate := func(name string, fn func(el *etree.Element)) {
		t.Run(name, func(t *testing.T) {
			el := spElement(t, sp.Copy())
			fn(el)
			if err := CheckSignedProperties(stdDM(), 0, el, p.Signer.Certificate, files); err == nil {
				t.Error("expected an error")
			}
		})
	}
	const certPath = "xades:SignedSignatureProperties/xades:SigningCertificate/xades:Cert"
	mutate("wrong-serial", func(el *etree.Element) {
		serial := el.FindElement(certPath + "/xades:IssuerSerial/ds:X509SerialNumber")
		serial.SetText(serial.Text() + "1")
	})
	mutate("wrong-issuer", func(el *etree.Element) {
		issuer := el.FindElement(certPath + "/xades:IssuerSerial/ds:X509IssuerName")
		issuer.SetText(issuer.Text() + "!")
	})
	mutate("unsupported-digest-method", func(el *etree.Element) {
		dm := el.FindElement(certPath + "/xades:CertDigest/ds:DigestMethod")
		dm.CreateAttr("Algorithm", "http://www.w3.org/2001/04/xmlenc#sha1")
	})
	mutate("signature-policy-identifier", func(el *etree.Element) {
		ssp := el.FindElement("xades:SignedSignatureProperties")
		ssp.CreateElement("xades:SignaturePolicyIdentifier")
	})
	mutate("mime-type-mismatch", func(el *etree.Element) {
		mt := el.FindElement("xades:SignedDataObjectProperties/xades:DataObjectFormat/xades:MimeType")
		mt.SetText("text/plain")
	})
}
