package xades

import (
	"encoding/base64"
	"regexp"
	"strings"
	"testing"

	"github.com/beevik/etree"
	"github.com/isri-pqc/asice/testutil"
)

// TestUnsignedPropertiesMatchesTSFixtureShape shape-compares the rendered
// UnsignedProperties against the USP subtree of the hermetic TS fixture
// testEIDTS.bdoc's META-INF/signatures0.xml: same element order,
// attributes (including the S0-T0 / S0-RESPONDER_CERT / S0-CA-CERT / N0
// Ids), and values.
//
// SELF-CONSISTENCY PIN: the fixture is generated by this repo's own
// testutil PKI via test/samples/gen; whitespace is ignored in the
// comparison — UnsignedProperties is outside both canonicalized
// regions, so layout there changes no digest (the external interop
// proof against the fixture lives in the companion asice-compat
// harness). The rendered layout itself is pinned by the golden layout
// test.
func TestUnsignedPropertiesMatchesTSFixtureShape(t *testing.T) {
	s := readFixtureSignature(t, "testEIDTS.bdoc")
	pi := strings.Index(s, "<xades:UnsignedProperties")
	pj := strings.Index(s, "</xades:UnsignedProperties>")
	if pi < 0 || pj < 0 {
		t.Fatal("xades:UnsignedProperties not found in fixture")
	}
	fixture := s[pi : pj+len("</xades:UnsignedProperties>")]

	tst := fixtureValue(t, fixture, "xades:EncapsulatedTimeStamp")
	var certs []Certificate
	for _, m := range encCertRE.FindAllStringSubmatch(fixture, -1) {
		der := fixtureValueAt(t, fixture, m)
		certs = append(certs, Certificate{ID: m[1], DER: der})
	}
	if len(certs) == 0 {
		t.Fatal("no EncapsulatedX509Certificate in fixture USP")
	}
	ocsp := fixtureValue(t, fixture, "xades:EncapsulatedOCSPValue")

	got, err := UnsignedProperties(0, tst, certs, ocsp)
	if err != nil {
		t.Fatal(err)
	}
	shapeEqual(t, "xades:UnsignedProperties", fixtureUSPElement(t, s), got)
}

// fixtureUSPElement parses the fixture signature document and returns its
// xades:UnsignedProperties element (the semantic fixture side of the
// shape comparison).
func fixtureUSPElement(t *testing.T, s string) *etree.Element {
	t.Helper()
	d := etree.NewDocument()
	if err := d.ReadFromString(s); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	el := d.FindElement("//xades:UnsignedProperties")
	if el == nil {
		t.Fatal("xades:UnsignedProperties not found in fixture")
	}
	return el
}

var encCertRE = regexp.MustCompile(`<xades:EncapsulatedX509Certificate Id="([^"]+)">`)

// fixtureValueAt decodes the base64 content of the element matched at
// m[0]'s position in s.
func fixtureValueAt(t *testing.T, s string, m []string) []byte {
	t.Helper()
	off, err := searchOffset(s, m[0])
	if err != nil {
		t.Fatal(err)
	}
	i := off + strings.IndexByte(s[off:], '>') + 1
	j := strings.Index(s[i:], "</xades:EncapsulatedX509Certificate>")
	data, err := base64d(s[i : i+j])
	if err != nil {
		t.Fatal(err)
	}
	return data
}

func searchOffset(s, sub string) (int, error) {
	i := strings.Index(s, sub)
	if i < 0 {
		return 0, errNotFound(sub)
	}
	return i, nil
}

func errNotFound(sub string) error { return errText(sub + " not found") }

type errText string

func (e errText) Error() string { return string(e) }

// renderUSPWrapper builds the golden's minimal signature document
// (asic:XAdESSignatures → ds:Signature → ds:Object →
// xades:QualifyingProperties → usp), indents it, and returns the
// serialized bytes.
func renderUSPWrapper(t *testing.T, usp *etree.Element) string {
	t.Helper()
	doc := etree.NewDocument()
	root := doc.CreateElement("asic:XAdESSignatures")
	root.CreateAttr("xmlns:asic", NSASIC)
	root.CreateAttr("xmlns:ds", NSDSIG)
	root.CreateAttr("xmlns:xades", NSXAdES)
	sig := root.CreateElement("ds:Signature")
	sig.CreateAttr("Id", "S0")
	obj := sig.CreateElement("ds:Object")
	qp := obj.CreateElement("xades:QualifyingProperties")
	qp.CreateAttr("Target", "#S0")
	qp.AddChild(usp)
	doc.Indent(2)
	s, err := doc.WriteToString()
	if err != nil {
		t.Fatalf("serialize USP wrapper: %v", err)
	}
	return s
}

// TestUnsignedPropertiesGoldenLayout pins the exact rendered bytes of
// UnsignedProperties for one deterministic input, so the 2-space indent /
// single-line base64 house layout cannot drift.
func TestUnsignedPropertiesGoldenLayout(t *testing.T) {
	p, err := testutil.NewPKI(testutil.Options{Now: testNow})
	if err != nil {
		t.Fatal(err)
	}
	tst, err := p.TimeStampToken([]byte("tst data"), testutil.TSTOptions{GenTime: testNow})
	if err != nil {
		t.Fatal(err)
	}
	ocsp, err := p.OCSPResponse(testNow)
	if err != nil {
		t.Fatal(err)
	}
	certs := []Certificate{
		{ID: ResponderCertificateID(0), DER: p.OCSPResponder.DER},
		{ID: CACertificateID(0), DER: p.Issuer.DER},
	}
	got, err := UnsignedProperties(0, tst, certs, ocsp)
	if err != nil {
		t.Fatal(err)
	}
	s := renderUSPWrapper(t, got)
	want := strings.NewReplacer(
		"@@TST@@", base64.StdEncoding.EncodeToString(tst),
		"@@RESPONDER@@", base64.StdEncoding.EncodeToString(p.OCSPResponder.DER),
		"@@CA@@", base64.StdEncoding.EncodeToString(p.Issuer.DER),
		"@@OCSP@@", base64.StdEncoding.EncodeToString(ocsp),
	).Replace(goldenUSPLayout)
	if s != want {
		t.Errorf("USP layout drifted:\n--- got ---\n%s\n--- want ---\n%s", s, want)
	}
}

const goldenUSPLayout = `<asic:XAdESSignatures xmlns:asic="http://uri.etsi.org/02918/v1.2.1#" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xades="http://uri.etsi.org/01903/v1.3.2#">
  <ds:Signature Id="S0">
    <ds:Object>
      <xades:QualifyingProperties Target="#S0">
        <xades:UnsignedProperties>
          <xades:UnsignedSignatureProperties>
            <xades:SignatureTimeStamp Id="S0-T0">
              <xades:EncapsulatedTimeStamp>@@TST@@</xades:EncapsulatedTimeStamp>
            </xades:SignatureTimeStamp>
            <xades:CertificateValues>
              <xades:EncapsulatedX509Certificate Id="S0-RESPONDER_CERT">@@RESPONDER@@</xades:EncapsulatedX509Certificate>
              <xades:EncapsulatedX509Certificate Id="S0-CA-CERT">@@CA@@</xades:EncapsulatedX509Certificate>
            </xades:CertificateValues>
            <xades:RevocationValues>
              <xades:OCSPValues>
                <xades:EncapsulatedOCSPValue Id="N0">@@OCSP@@</xades:EncapsulatedOCSPValue>
              </xades:OCSPValues>
            </xades:RevocationValues>
          </xades:UnsignedSignatureProperties>
        </xades:UnsignedProperties>
      </xades:QualifyingProperties>
    </ds:Object>
  </ds:Signature>
</asic:XAdESSignatures>
`

// TestUnsignedPropertiesRejectsEmptyInput checks the input guards.
func TestUnsignedPropertiesRejectsEmptyInput(t *testing.T) {
	certs := []Certificate{{ID: "x", DER: []byte{1}}}
	if _, err := UnsignedProperties(0, nil, certs, []byte{1}); err == nil {
		t.Error("expected error for empty TST")
	}
	if _, err := UnsignedProperties(0, []byte{1}, nil, []byte{1}); err == nil {
		t.Error("expected error for no certificates")
	}
	if _, err := UnsignedProperties(0, []byte{1}, certs, nil); err == nil {
		t.Error("expected error for empty OCSP")
	}
	if _, err := UnsignedProperties(0, []byte{1}, []Certificate{{ID: "x"}}, []byte{1}); err == nil {
		t.Error("expected error for certificate without DER")
	}
}

// base64d decodes whitespace-trimmed standard base64, the way the
// Estonian e-voting collector decodes base64 values (TrimSpace then
// decode).
func base64d(s string) ([]byte, error) {
	return base64.StdEncoding.DecodeString(strings.TrimSpace(s))
}
